name: mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  icons_plus: ^4.0.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  get_it: ^7.6.0
  appinio_swiper: ^2.1.0
  flutter_card_swiper: ^6.1.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  floor_generator: ^1.4.2
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
